/*
 * Token Connect API
 *
 * The MDES APIs are designed as RPC style stateless web services where each API endpoint represents an operation to be performed. All request and response payloads are sent in the JSON (JavaScript Object Notation) data-interchange format. Each endpoint in the API specifies the HTTP Method used to access it. All strings in request and response objects are to be UTF-8 encoded. 
 *
 * The version of the OpenAPI document: 2.03
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MastercardApi.Client.Api;
using MastercardApi.Client.Model;
using MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing AccountHolder
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountHolderTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccountHolder
        //private AccountHolder instance;

        public AccountHolderTests()
        {
            // TODO uncomment below to create an instance of AccountHolder
            //instance = new AccountHolder();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountHolder
        /// </summary>
        [Fact]
        public void AccountHolderInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccountHolder
            //Assert.IsType<AccountHolder>(instance);
        }


        /// <summary>
        /// Test the property 'AccountHolderName'
        /// </summary>
        [Fact]
        public void AccountHolderNameTest()
        {
            // TODO unit test for the property 'AccountHolderName'
        }
        /// <summary>
        /// Test the property 'AccountHolderAddress'
        /// </summary>
        [Fact]
        public void AccountHolderAddressTest()
        {
            // TODO unit test for the property 'AccountHolderAddress'
        }
        /// <summary>
        /// Test the property 'AccountHolderEmailAddress'
        /// </summary>
        [Fact]
        public void AccountHolderEmailAddressTest()
        {
            // TODO unit test for the property 'AccountHolderEmailAddress'
        }
        /// <summary>
        /// Test the property 'AccountHolderMobilePhoneNumber'
        /// </summary>
        [Fact]
        public void AccountHolderMobilePhoneNumberTest()
        {
            // TODO unit test for the property 'AccountHolderMobilePhoneNumber'
        }

    }

}
