/*
 * Token Connect API
 *
 * The MDES APIs are designed as RPC style stateless web services where each API endpoint represents an operation to be performed. All request and response payloads are sent in the JSON (JavaScript Object Notation) data-interchange format. Each endpoint in the API specifies the HTTP Method used to access it. All strings in request and response objects are to be UTF-8 encoded. 
 *
 * The version of the OpenAPI document: 2.03
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MastercardApi.Client.Api;
using MastercardApi.Client.Model;
using MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing AssetResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssetResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AssetResponse
        //private AssetResponse instance;

        public AssetResponseTests()
        {
            // TODO uncomment below to create an instance of AssetResponse
            //instance = new AssetResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssetResponse
        /// </summary>
        [Fact]
        public void AssetResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AssetResponse
            //Assert.IsType<AssetResponse>(instance);
        }


        /// <summary>
        /// Test the property 'MediaContents'
        /// </summary>
        [Fact]
        public void MediaContentsTest()
        {
            // TODO unit test for the property 'MediaContents'
        }

    }

}
