/*
 * Token Connect API
 *
 * The MDES APIs are designed as RPC style stateless web services where each API endpoint represents an operation to be performed. All request and response payloads are sent in the JSON (JavaScript Object Notation) data-interchange format. Each endpoint in the API specifies the HTTP Method used to access it. All strings in request and response objects are to be UTF-8 encoded. 
 *
 * The version of the OpenAPI document: 2.03
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MastercardApi.Client.Api;
using MastercardApi.Client.Model;
using MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing BillingAddress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BillingAddressTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BillingAddress
        //private BillingAddress instance;

        public BillingAddressTests()
        {
            // TODO uncomment below to create an instance of BillingAddress
            //instance = new BillingAddress();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BillingAddress
        /// </summary>
        [Fact]
        public void BillingAddressInstanceTest()
        {
            // TODO uncomment below to test "IsType" BillingAddress
            //Assert.IsType<BillingAddress>(instance);
        }


        /// <summary>
        /// Test the property 'Line1'
        /// </summary>
        [Fact]
        public void Line1Test()
        {
            // TODO unit test for the property 'Line1'
        }
        /// <summary>
        /// Test the property 'Line2'
        /// </summary>
        [Fact]
        public void Line2Test()
        {
            // TODO unit test for the property 'Line2'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'CountrySubdivision'
        /// </summary>
        [Fact]
        public void CountrySubdivisionTest()
        {
            // TODO unit test for the property 'CountrySubdivision'
        }
        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Fact]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

    }

}
