/*
 * Token Connect API
 *
 * The MDES APIs are designed as RPC style stateless web services where each API endpoint represents an operation to be performed. All request and response payloads are sent in the JSON (JavaScript Object Notation) data-interchange format. Each endpoint in the API specifies the HTTP Method used to access it. All strings in request and response objects are to be UTF-8 encoded. 
 *
 * The version of the OpenAPI document: 2.03
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MastercardApi.Client.Api;
using MastercardApi.Client.Model;
using MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing CardAccount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CardAccountTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CardAccount
        //private CardAccount instance;

        public CardAccountTests()
        {
            // TODO uncomment below to create an instance of CardAccount
            //instance = new CardAccount();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CardAccount
        /// </summary>
        [Fact]
        public void CardAccountInstanceTest()
        {
            // TODO uncomment below to test "IsType" CardAccount
            //Assert.IsType<CardAccount>(instance);
        }


        /// <summary>
        /// Test the property 'AccountNumber'
        /// </summary>
        [Fact]
        public void AccountNumberTest()
        {
            // TODO unit test for the property 'AccountNumber'
        }
        /// <summary>
        /// Test the property 'ExpiryMonth'
        /// </summary>
        [Fact]
        public void ExpiryMonthTest()
        {
            // TODO unit test for the property 'ExpiryMonth'
        }
        /// <summary>
        /// Test the property 'ExpiryYear'
        /// </summary>
        [Fact]
        public void ExpiryYearTest()
        {
            // TODO unit test for the property 'ExpiryYear'
        }

    }

}
