/*
 * Token Connect API
 *
 * The MDES APIs are designed as RPC style stateless web services where each API endpoint represents an operation to be performed. All request and response payloads are sent in the JSON (JavaScript Object Notation) data-interchange format. Each endpoint in the API specifies the HTTP Method used to access it. All strings in request and response objects are to be UTF-8 encoded. 
 *
 * The version of the OpenAPI document: 2.03
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MastercardApi.Client.Api;
using MastercardApi.Client.Model;
using MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EncryptedPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EncryptedPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EncryptedPayload
        //private EncryptedPayload instance;

        public EncryptedPayloadTests()
        {
            // TODO uncomment below to create an instance of EncryptedPayload
            //instance = new EncryptedPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EncryptedPayload
        /// </summary>
        [Fact]
        public void EncryptedPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" EncryptedPayload
            //Assert.IsType<EncryptedPayload>(instance);
        }


        /// <summary>
        /// Test the property 'EncryptedData'
        /// </summary>
        [Fact]
        public void EncryptedDataTest()
        {
            // TODO unit test for the property 'EncryptedData'
        }
        /// <summary>
        /// Test the property 'PublicKeyFingerprint'
        /// </summary>
        [Fact]
        public void PublicKeyFingerprintTest()
        {
            // TODO unit test for the property 'PublicKeyFingerprint'
        }
        /// <summary>
        /// Test the property 'EncryptedKey'
        /// </summary>
        [Fact]
        public void EncryptedKeyTest()
        {
            // TODO unit test for the property 'EncryptedKey'
        }
        /// <summary>
        /// Test the property 'OaepHashingAlgorithm'
        /// </summary>
        [Fact]
        public void OaepHashingAlgorithmTest()
        {
            // TODO unit test for the property 'OaepHashingAlgorithm'
        }
        /// <summary>
        /// Test the property 'Iv'
        /// </summary>
        [Fact]
        public void IvTest()
        {
            // TODO unit test for the property 'Iv'
        }

    }

}
