/*
 * Token Connect API
 *
 * The MDES APIs are designed as RPC style stateless web services where each API endpoint represents an operation to be performed. All request and response payloads are sent in the JSON (JavaScript Object Notation) data-interchange format. Each endpoint in the API specifies the HTTP Method used to access it. All strings in request and response objects are to be UTF-8 encoded. 
 *
 * The version of the OpenAPI document: 2.03
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MastercardApi.Client.Api;
using MastercardApi.Client.Model;
using MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ErrorWrapper
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ErrorWrapperTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ErrorWrapper
        //private ErrorWrapper instance;

        public ErrorWrapperTests()
        {
            // TODO uncomment below to create an instance of ErrorWrapper
            //instance = new ErrorWrapper();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ErrorWrapper
        /// </summary>
        [Fact]
        public void ErrorWrapperInstanceTest()
        {
            // TODO uncomment below to test "IsType" ErrorWrapper
            //Assert.IsType<ErrorWrapper>(instance);
        }


        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
        /// <summary>
        /// Test the property 'ResponseId'
        /// </summary>
        [Fact]
        public void ResponseIdTest()
        {
            // TODO unit test for the property 'ResponseId'
        }

    }

}
