/*
 * Token Connect API
 *
 * The MDES APIs are designed as RPC style stateless web services where each API endpoint represents an operation to be performed. All request and response payloads are sent in the JSON (JavaScript Object Notation) data-interchange format. Each endpoint in the API specifies the HTTP Method used to access it. All strings in request and response objects are to be UTF-8 encoded. 
 *
 * The version of the OpenAPI document: 2.03
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MastercardApi.Client.Api;
using MastercardApi.Client.Model;
using MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing GetEligibleTokenRequestorsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetEligibleTokenRequestorsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetEligibleTokenRequestorsRequest
        //private GetEligibleTokenRequestorsRequest instance;

        public GetEligibleTokenRequestorsRequestTests()
        {
            // TODO uncomment below to create an instance of GetEligibleTokenRequestorsRequest
            //instance = new GetEligibleTokenRequestorsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetEligibleTokenRequestorsRequest
        /// </summary>
        [Fact]
        public void GetEligibleTokenRequestorsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetEligibleTokenRequestorsRequest
            //Assert.IsType<GetEligibleTokenRequestorsRequest>(instance);
        }


        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Fact]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }
        /// <summary>
        /// Test the property 'AccountRanges'
        /// </summary>
        [Fact]
        public void AccountRangesTest()
        {
            // TODO unit test for the property 'AccountRanges'
        }
        /// <summary>
        /// Test the property 'SupportsTokenConnect'
        /// </summary>
        [Fact]
        public void SupportsTokenConnectTest()
        {
            // TODO unit test for the property 'SupportsTokenConnect'
        }

    }

}
