/*
 * Token Connect API
 *
 * The MDES APIs are designed as RPC style stateless web services where each API endpoint represents an operation to be performed. All request and response payloads are sent in the JSON (JavaScript Object Notation) data-interchange format. Each endpoint in the API specifies the HTTP Method used to access it. All strings in request and response objects are to be UTF-8 encoded. 
 *
 * The version of the OpenAPI document: 2.03
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MastercardApi.Client.Api;
using MastercardApi.Client.Model;
using MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing PushAccountRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PushAccountRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PushAccountRequest
        //private PushAccountRequest instance;

        public PushAccountRequestTests()
        {
            // TODO uncomment below to create an instance of PushAccountRequest
            //instance = new PushAccountRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PushAccountRequest
        /// </summary>
        [Fact]
        public void PushAccountRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PushAccountRequest
            //Assert.IsType<PushAccountRequest>(instance);
        }


        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Fact]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }
        /// <summary>
        /// Test the property 'PushFundingAccount'
        /// </summary>
        [Fact]
        public void PushFundingAccountTest()
        {
            // TODO unit test for the property 'PushFundingAccount'
        }
        /// <summary>
        /// Test the property 'TokenRequestorId'
        /// </summary>
        [Fact]
        public void TokenRequestorIdTest()
        {
            // TODO unit test for the property 'TokenRequestorId'
        }

    }

}
