/*
 * Token Connect API
 *
 * The MDES APIs are designed as RPC style stateless web services where each API endpoint represents an operation to be performed. All request and response payloads are sent in the JSON (JavaScript Object Notation) data-interchange format. Each endpoint in the API specifies the HTTP Method used to access it. All strings in request and response objects are to be UTF-8 encoded. 
 *
 * The version of the OpenAPI document: 2.03
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MastercardApi.Client.Api;
using MastercardApi.Client.Model;
using MastercardApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MastercardApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing PushAccountResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PushAccountResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PushAccountResponse
        //private PushAccountResponse instance;

        public PushAccountResponseTests()
        {
            // TODO uncomment below to create an instance of PushAccountResponse
            //instance = new PushAccountResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PushAccountResponse
        /// </summary>
        [Fact]
        public void PushAccountResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PushAccountResponse
            //Assert.IsType<PushAccountResponse>(instance);
        }


        /// <summary>
        /// Test the property 'ResponseId'
        /// </summary>
        [Fact]
        public void ResponseIdTest()
        {
            // TODO unit test for the property 'ResponseId'
        }
        /// <summary>
        /// Test the property 'PushAccountReceipt'
        /// </summary>
        [Fact]
        public void PushAccountReceiptTest()
        {
            // TODO unit test for the property 'PushAccountReceipt'
        }
        /// <summary>
        /// Test the property 'AvailablePushMethods'
        /// </summary>
        [Fact]
        public void AvailablePushMethodsTest()
        {
            // TODO unit test for the property 'AvailablePushMethods'
        }
        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }

    }

}
