/*
 * Token Connect API
 *
 * The MDES APIs are designed as RPC style stateless web services where each API endpoint represents an operation to be performed. All request and response payloads are sent in the JSON (JavaScript Object Notation) data-interchange format. Each endpoint in the API specifies the HTTP Method used to access it. All strings in request and response objects are to be UTF-8 encoded. 
 *
 * The version of the OpenAPI document: 2.03
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MastercardApi.Client.Client.OpenAPIDateConverter;

namespace MastercardApi.Client.Model
{
    /// <summary>
    /// AssetResponse
    /// </summary>
    [DataContract(Name = "AssetResponse")]
    public partial class AssetResponse : IEquatable<AssetResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AssetResponse" /> class.
        /// </summary>
        /// <param name="mediaContents">Contains all contents of the Asset, including all variations. When the Asset corresponds to a Token Requestor&#39;s logo, the logo is provided both in .svg as well as in .png format.</param>
        public AssetResponse(List<MediaContent> mediaContents = default(List<MediaContent>))
        {
            this.MediaContents = mediaContents;
        }

        /// <summary>
        /// Contains all contents of the Asset, including all variations. When the Asset corresponds to a Token Requestor&#39;s logo, the logo is provided both in .svg as well as in .png format
        /// </summary>
        /// <value>Contains all contents of the Asset, including all variations. When the Asset corresponds to a Token Requestor&#39;s logo, the logo is provided both in .svg as well as in .png format</value>
        [DataMember(Name = "mediaContents", EmitDefaultValue = false)]
        public List<MediaContent> MediaContents { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AssetResponse {\n");
            sb.Append("  MediaContents: ").Append(MediaContents).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AssetResponse);
        }

        /// <summary>
        /// Returns true if AssetResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of AssetResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AssetResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.MediaContents == input.MediaContents ||
                    this.MediaContents != null &&
                    input.MediaContents != null &&
                    this.MediaContents.SequenceEqual(input.MediaContents)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MediaContents != null)
                    hashCode = hashCode * 59 + this.MediaContents.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
