/*
 * Token Connect API
 *
 * The MDES APIs are designed as RPC style stateless web services where each API endpoint represents an operation to be performed. All request and response payloads are sent in the JSON (JavaScript Object Notation) data-interchange format. Each endpoint in the API specifies the HTTP Method used to access it. All strings in request and response objects are to be UTF-8 encoded. 
 *
 * The version of the OpenAPI document: 2.03
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MastercardApi.Client.Client.OpenAPIDateConverter;

namespace MastercardApi.Client.Model
{
    /// <summary>
    /// FinancialAccount
    /// </summary>
    [DataContract(Name = "FinancialAccount")]
    public partial class FinancialAccount : IEquatable<FinancialAccount>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FinancialAccount" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FinancialAccount() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FinancialAccount" /> class.
        /// </summary>
        /// <param name="financialAccountId">The identifier of the financial account being tokenized.This could be a bank account number or other types of financial accounts. __Max length:__ 64 -  __Min length:__ 9. __Data Type:__ String (spaces not allowed).  (required).</param>
        /// <param name="interbankCardAssociationId">The identifier (ICA) assigned by Mastercard to the financial institution. __Max length:__ 11 -  __Min length:__ 3. __Data Type:__ String (Numeric).  (required).</param>
        /// <param name="countryCode">The country of the financial account. Expressed as a 3-letter (alpha-3) country code as defined in ISO 3166-1. __Length:__ 3  (required).</param>
        public FinancialAccount(string financialAccountId = default(string), string interbankCardAssociationId = default(string), string countryCode = default(string))
        {
            // to ensure "financialAccountId" is required (not null)
            if (financialAccountId == null) {
                throw new ArgumentNullException("financialAccountId is a required property for FinancialAccount and cannot be null");
            }
            this.FinancialAccountId = financialAccountId;
            // to ensure "interbankCardAssociationId" is required (not null)
            if (interbankCardAssociationId == null) {
                throw new ArgumentNullException("interbankCardAssociationId is a required property for FinancialAccount and cannot be null");
            }
            this.InterbankCardAssociationId = interbankCardAssociationId;
            // to ensure "countryCode" is required (not null)
            if (countryCode == null) {
                throw new ArgumentNullException("countryCode is a required property for FinancialAccount and cannot be null");
            }
            this.CountryCode = countryCode;
        }

        /// <summary>
        /// The identifier of the financial account being tokenized.This could be a bank account number or other types of financial accounts. __Max length:__ 64 -  __Min length:__ 9. __Data Type:__ String (spaces not allowed). 
        /// </summary>
        /// <value>The identifier of the financial account being tokenized.This could be a bank account number or other types of financial accounts. __Max length:__ 64 -  __Min length:__ 9. __Data Type:__ String (spaces not allowed). </value>
        [DataMember(Name = "financialAccountId", IsRequired = true, EmitDefaultValue = false)]
        public string FinancialAccountId { get; set; }

        /// <summary>
        /// The identifier (ICA) assigned by Mastercard to the financial institution. __Max length:__ 11 -  __Min length:__ 3. __Data Type:__ String (Numeric). 
        /// </summary>
        /// <value>The identifier (ICA) assigned by Mastercard to the financial institution. __Max length:__ 11 -  __Min length:__ 3. __Data Type:__ String (Numeric). </value>
        [DataMember(Name = "interbankCardAssociationId", IsRequired = true, EmitDefaultValue = false)]
        public string InterbankCardAssociationId { get; set; }

        /// <summary>
        /// The country of the financial account. Expressed as a 3-letter (alpha-3) country code as defined in ISO 3166-1. __Length:__ 3 
        /// </summary>
        /// <value>The country of the financial account. Expressed as a 3-letter (alpha-3) country code as defined in ISO 3166-1. __Length:__ 3 </value>
        [DataMember(Name = "countryCode", IsRequired = true, EmitDefaultValue = false)]
        public string CountryCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FinancialAccount {\n");
            sb.Append("  FinancialAccountId: ").Append(FinancialAccountId).Append("\n");
            sb.Append("  InterbankCardAssociationId: ").Append(InterbankCardAssociationId).Append("\n");
            sb.Append("  CountryCode: ").Append(CountryCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FinancialAccount);
        }

        /// <summary>
        /// Returns true if FinancialAccount instances are equal
        /// </summary>
        /// <param name="input">Instance of FinancialAccount to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FinancialAccount input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FinancialAccountId == input.FinancialAccountId ||
                    (this.FinancialAccountId != null &&
                    this.FinancialAccountId.Equals(input.FinancialAccountId))
                ) && 
                (
                    this.InterbankCardAssociationId == input.InterbankCardAssociationId ||
                    (this.InterbankCardAssociationId != null &&
                    this.InterbankCardAssociationId.Equals(input.InterbankCardAssociationId))
                ) && 
                (
                    this.CountryCode == input.CountryCode ||
                    (this.CountryCode != null &&
                    this.CountryCode.Equals(input.CountryCode))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FinancialAccountId != null)
                    hashCode = hashCode * 59 + this.FinancialAccountId.GetHashCode();
                if (this.InterbankCardAssociationId != null)
                    hashCode = hashCode * 59 + this.InterbankCardAssociationId.GetHashCode();
                if (this.CountryCode != null)
                    hashCode = hashCode * 59 + this.CountryCode.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
