/*
 * Token Connect API
 *
 * The MDES APIs are designed as RPC style stateless web services where each API endpoint represents an operation to be performed. All request and response payloads are sent in the JSON (JavaScript Object Notation) data-interchange format. Each endpoint in the API specifies the HTTP Method used to access it. All strings in request and response objects are to be UTF-8 encoded. 
 *
 * The version of the OpenAPI document: 2.03
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MastercardApi.Client.Client.OpenAPIDateConverter;

namespace MastercardApi.Client.Model
{
    /// <summary>
    /// GetEligibleTokenRequestorsResponse
    /// </summary>
    [DataContract(Name = "GetEligibleTokenRequestorsResponse")]
    public partial class GetEligibleTokenRequestorsResponse : IEquatable<GetEligibleTokenRequestorsResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetEligibleTokenRequestorsResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetEligibleTokenRequestorsResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetEligibleTokenRequestorsResponse" /> class.
        /// </summary>
        /// <param name="responseId">Unique identifier for the response matching the requestId supplied in the request. __Max Length:__ 64  (required).</param>
        /// <param name="tokenRequestors">The array of Token Requestors that are eligible for the account ranges in the request. __Conditional.__ Required if the operation was successful. .</param>
        /// <param name="errors">Element encapsulating a collection of errors that occurred during a single request. __Conditional.__ Required if one or more errors occurred while performing the operation. Not present if the operation was successful. .</param>
        public GetEligibleTokenRequestorsResponse(string responseId = default(string), List<TokenRequestor> tokenRequestors = default(List<TokenRequestor>), List<Error> errors = default(List<Error>))
        {
            // to ensure "responseId" is required (not null)
            if (responseId == null) {
                throw new ArgumentNullException("responseId is a required property for GetEligibleTokenRequestorsResponse and cannot be null");
            }
            this.ResponseId = responseId;
            this.TokenRequestors = tokenRequestors;
            this.Errors = errors;
        }

        /// <summary>
        /// Unique identifier for the response matching the requestId supplied in the request. __Max Length:__ 64 
        /// </summary>
        /// <value>Unique identifier for the response matching the requestId supplied in the request. __Max Length:__ 64 </value>
        [DataMember(Name = "responseId", IsRequired = true, EmitDefaultValue = false)]
        public string ResponseId { get; set; }

        /// <summary>
        /// The array of Token Requestors that are eligible for the account ranges in the request. __Conditional.__ Required if the operation was successful. 
        /// </summary>
        /// <value>The array of Token Requestors that are eligible for the account ranges in the request. __Conditional.__ Required if the operation was successful. </value>
        [DataMember(Name = "tokenRequestors", EmitDefaultValue = false)]
        public List<TokenRequestor> TokenRequestors { get; set; }

        /// <summary>
        /// Element encapsulating a collection of errors that occurred during a single request. __Conditional.__ Required if one or more errors occurred while performing the operation. Not present if the operation was successful. 
        /// </summary>
        /// <value>Element encapsulating a collection of errors that occurred during a single request. __Conditional.__ Required if one or more errors occurred while performing the operation. Not present if the operation was successful. </value>
        [DataMember(Name = "errors", EmitDefaultValue = false)]
        public List<Error> Errors { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetEligibleTokenRequestorsResponse {\n");
            sb.Append("  ResponseId: ").Append(ResponseId).Append("\n");
            sb.Append("  TokenRequestors: ").Append(TokenRequestors).Append("\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetEligibleTokenRequestorsResponse);
        }

        /// <summary>
        /// Returns true if GetEligibleTokenRequestorsResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of GetEligibleTokenRequestorsResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetEligibleTokenRequestorsResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ResponseId == input.ResponseId ||
                    (this.ResponseId != null &&
                    this.ResponseId.Equals(input.ResponseId))
                ) && 
                (
                    this.TokenRequestors == input.TokenRequestors ||
                    this.TokenRequestors != null &&
                    input.TokenRequestors != null &&
                    this.TokenRequestors.SequenceEqual(input.TokenRequestors)
                ) && 
                (
                    this.Errors == input.Errors ||
                    this.Errors != null &&
                    input.Errors != null &&
                    this.Errors.SequenceEqual(input.Errors)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ResponseId != null)
                    hashCode = hashCode * 59 + this.ResponseId.GetHashCode();
                if (this.TokenRequestors != null)
                    hashCode = hashCode * 59 + this.TokenRequestors.GetHashCode();
                if (this.Errors != null)
                    hashCode = hashCode * 59 + this.Errors.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
