/*
 * Token Connect API
 *
 * The MDES APIs are designed as RPC style stateless web services where each API endpoint represents an operation to be performed. All request and response payloads are sent in the JSON (JavaScript Object Notation) data-interchange format. Each endpoint in the API specifies the HTTP Method used to access it. All strings in request and response objects are to be UTF-8 encoded. 
 *
 * The version of the OpenAPI document: 2.03
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MastercardApi.Client.Client.OpenAPIDateConverter;

namespace MastercardApi.Client.Model
{
    /// <summary>
    /// CardAccount
    /// </summary>
    [DataContract(Name = "CardAccount")]
    public partial class CardAccount : IEquatable<CardAccount>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CardAccount" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CardAccount() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CardAccount" /> class.
        /// </summary>
        /// <param name="accountNumber">The Account Primary Account Number of the card to be digitized. __Max length:__ 19 -  __Min length:__ 9. __Data Type:__ String (Numeric)  (required).</param>
        /// <param name="expiryMonth">The month of the expiration date of the card to be digitized. Note that the expiry date may not be in the past. May be omitted if the card does not have an expiry date. __Length:__ 2 __Data Type:__ String (Numeric) .</param>
        /// <param name="expiryYear">The year of the expiration date of the card to be digitized. Note that the expiry date may not be in the past. May be omitted if the card does not have an expiry date. __Length:__ 2 __Data Type:__ String (Numeric) .</param>
        public CardAccount(string accountNumber = default(string), string expiryMonth = default(string), string expiryYear = default(string))
        {
            // to ensure "accountNumber" is required (not null)
            if (accountNumber == null) {
                throw new ArgumentNullException("accountNumber is a required property for CardAccount and cannot be null");
            }
            this.AccountNumber = accountNumber;
            this.ExpiryMonth = expiryMonth;
            this.ExpiryYear = expiryYear;
        }

        /// <summary>
        /// The Account Primary Account Number of the card to be digitized. __Max length:__ 19 -  __Min length:__ 9. __Data Type:__ String (Numeric) 
        /// </summary>
        /// <value>The Account Primary Account Number of the card to be digitized. __Max length:__ 19 -  __Min length:__ 9. __Data Type:__ String (Numeric) </value>
        [DataMember(Name = "accountNumber", IsRequired = true, EmitDefaultValue = false)]
        public string AccountNumber { get; set; }

        /// <summary>
        /// The month of the expiration date of the card to be digitized. Note that the expiry date may not be in the past. May be omitted if the card does not have an expiry date. __Length:__ 2 __Data Type:__ String (Numeric) 
        /// </summary>
        /// <value>The month of the expiration date of the card to be digitized. Note that the expiry date may not be in the past. May be omitted if the card does not have an expiry date. __Length:__ 2 __Data Type:__ String (Numeric) </value>
        [DataMember(Name = "expiryMonth", EmitDefaultValue = false)]
        public string ExpiryMonth { get; set; }

        /// <summary>
        /// The year of the expiration date of the card to be digitized. Note that the expiry date may not be in the past. May be omitted if the card does not have an expiry date. __Length:__ 2 __Data Type:__ String (Numeric) 
        /// </summary>
        /// <value>The year of the expiration date of the card to be digitized. Note that the expiry date may not be in the past. May be omitted if the card does not have an expiry date. __Length:__ 2 __Data Type:__ String (Numeric) </value>
        [DataMember(Name = "expiryYear", EmitDefaultValue = false)]
        public string ExpiryYear { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CardAccount {\n");
            sb.Append("  AccountNumber: ").Append(AccountNumber).Append("\n");
            sb.Append("  ExpiryMonth: ").Append(ExpiryMonth).Append("\n");
            sb.Append("  ExpiryYear: ").Append(ExpiryYear).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CardAccount);
        }

        /// <summary>
        /// Returns true if CardAccount instances are equal
        /// </summary>
        /// <param name="input">Instance of CardAccount to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CardAccount input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AccountNumber == input.AccountNumber ||
                    (this.AccountNumber != null &&
                    this.AccountNumber.Equals(input.AccountNumber))
                ) && 
                (
                    this.ExpiryMonth == input.ExpiryMonth ||
                    (this.ExpiryMonth != null &&
                    this.ExpiryMonth.Equals(input.ExpiryMonth))
                ) && 
                (
                    this.ExpiryYear == input.ExpiryYear ||
                    (this.ExpiryYear != null &&
                    this.ExpiryYear.Equals(input.ExpiryYear))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AccountNumber != null)
                    hashCode = hashCode * 59 + this.AccountNumber.GetHashCode();
                if (this.ExpiryMonth != null)
                    hashCode = hashCode * 59 + this.ExpiryMonth.GetHashCode();
                if (this.ExpiryYear != null)
                    hashCode = hashCode * 59 + this.ExpiryYear.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
