/*
 * Token Connect API
 *
 * The MDES APIs are designed as RPC style stateless web services where each API endpoint represents an operation to be performed. All request and response payloads are sent in the JSON (JavaScript Object Notation) data-interchange format. Each endpoint in the API specifies the HTTP Method used to access it. All strings in request and response objects are to be UTF-8 encoded. 
 *
 * The version of the OpenAPI document: 2.03
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MastercardApi.Client.Client.OpenAPIDateConverter;

namespace MastercardApi.Client.Model
{
    /// <summary>
    /// FundingAccount
    /// </summary>
    [DataContract(Name = "FundingAccount")]
    public partial class FundingAccount : IEquatable<FundingAccount>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FundingAccount" /> class.
        /// </summary>
        /// <param name="cardAccountData">cardAccountData.</param>
        /// <param name="financialAccountData">financialAccountData.</param>
        /// <param name="accountHolderData">accountHolderData.</param>
        /// <param name="dataValidUntilTimestamp">The date/time after which this encrypted payload object is considered invalid. If present, all systems must reject this encrypted object after this time and treat it as invalid data. Must be a value no more than 30 days in the future. Mastercard recommends using a value of (CurrentTime + 30 minutes). __Max length:__ 29. Must be expressed in ISO 8601 extended format as one of the following: * YYYY-MM-DDThh:mm:ss[.sss]Z * YYYY-MM-DDThh:mm:ss[.sss]±hh:mm where [.sss] is optional and can be 1 to 3 digits. .</param>
        public FundingAccount(CardAccount cardAccountData = default(CardAccount), FinancialAccount financialAccountData = default(FinancialAccount), AccountHolder accountHolderData = default(AccountHolder), string dataValidUntilTimestamp = default(string))
        {
            this.CardAccountData = cardAccountData;
            this.FinancialAccountData = financialAccountData;
            this.AccountHolderData = accountHolderData;
            this.DataValidUntilTimestamp = dataValidUntilTimestamp;
        }

        /// <summary>
        /// Gets or Sets CardAccountData
        /// </summary>
        [DataMember(Name = "cardAccountData", EmitDefaultValue = false)]
        public CardAccount CardAccountData { get; set; }

        /// <summary>
        /// Gets or Sets FinancialAccountData
        /// </summary>
        [DataMember(Name = "financialAccountData", EmitDefaultValue = false)]
        public FinancialAccount FinancialAccountData { get; set; }

        /// <summary>
        /// Gets or Sets AccountHolderData
        /// </summary>
        [DataMember(Name = "accountHolderData", EmitDefaultValue = false)]
        public AccountHolder AccountHolderData { get; set; }

        /// <summary>
        /// The date/time after which this encrypted payload object is considered invalid. If present, all systems must reject this encrypted object after this time and treat it as invalid data. Must be a value no more than 30 days in the future. Mastercard recommends using a value of (CurrentTime + 30 minutes). __Max length:__ 29. Must be expressed in ISO 8601 extended format as one of the following: * YYYY-MM-DDThh:mm:ss[.sss]Z * YYYY-MM-DDThh:mm:ss[.sss]±hh:mm where [.sss] is optional and can be 1 to 3 digits. 
        /// </summary>
        /// <value>The date/time after which this encrypted payload object is considered invalid. If present, all systems must reject this encrypted object after this time and treat it as invalid data. Must be a value no more than 30 days in the future. Mastercard recommends using a value of (CurrentTime + 30 minutes). __Max length:__ 29. Must be expressed in ISO 8601 extended format as one of the following: * YYYY-MM-DDThh:mm:ss[.sss]Z * YYYY-MM-DDThh:mm:ss[.sss]±hh:mm where [.sss] is optional and can be 1 to 3 digits. </value>
        [DataMember(Name = "dataValidUntilTimestamp", EmitDefaultValue = false)]
        public string DataValidUntilTimestamp { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FundingAccount {\n");
            sb.Append("  CardAccountData: ").Append(CardAccountData).Append("\n");
            sb.Append("  FinancialAccountData: ").Append(FinancialAccountData).Append("\n");
            sb.Append("  AccountHolderData: ").Append(AccountHolderData).Append("\n");
            sb.Append("  DataValidUntilTimestamp: ").Append(DataValidUntilTimestamp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FundingAccount);
        }

        /// <summary>
        /// Returns true if FundingAccount instances are equal
        /// </summary>
        /// <param name="input">Instance of FundingAccount to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FundingAccount input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CardAccountData == input.CardAccountData ||
                    (this.CardAccountData != null &&
                    this.CardAccountData.Equals(input.CardAccountData))
                ) && 
                (
                    this.FinancialAccountData == input.FinancialAccountData ||
                    (this.FinancialAccountData != null &&
                    this.FinancialAccountData.Equals(input.FinancialAccountData))
                ) && 
                (
                    this.AccountHolderData == input.AccountHolderData ||
                    (this.AccountHolderData != null &&
                    this.AccountHolderData.Equals(input.AccountHolderData))
                ) && 
                (
                    this.DataValidUntilTimestamp == input.DataValidUntilTimestamp ||
                    (this.DataValidUntilTimestamp != null &&
                    this.DataValidUntilTimestamp.Equals(input.DataValidUntilTimestamp))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CardAccountData != null)
                    hashCode = hashCode * 59 + this.CardAccountData.GetHashCode();
                if (this.FinancialAccountData != null)
                    hashCode = hashCode * 59 + this.FinancialAccountData.GetHashCode();
                if (this.AccountHolderData != null)
                    hashCode = hashCode * 59 + this.AccountHolderData.GetHashCode();
                if (this.DataValidUntilTimestamp != null)
                    hashCode = hashCode * 59 + this.DataValidUntilTimestamp.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
