/*
 * Token Connect API
 *
 * The MDES APIs are designed as RPC style stateless web services where each API endpoint represents an operation to be performed. All request and response payloads are sent in the JSON (JavaScript Object Notation) data-interchange format. Each endpoint in the API specifies the HTTP Method used to access it. All strings in request and response objects are to be UTF-8 encoded. 
 *
 * The version of the OpenAPI document: 2.03
 * Contact: apisupport@mastercard.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MastercardApi.Client.Client.OpenAPIDateConverter;

namespace MastercardApi.Client.Model
{
    /// <summary>
    /// The information that MDES returns for each Token Requestor, when it is enabled for at least one of the Issuer&#39;s input account range
    /// </summary>
    [DataContract(Name = "TokenRequestor")]
    public partial class TokenRequestor : IEquatable<TokenRequestor>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TokenRequestor" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TokenRequestor() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TokenRequestor" /> class.
        /// </summary>
        /// <param name="tokenRequestorId">Identifies the Token Requestor where the Account must be pushed to. The string contains a 11-digit numeric value. __Length:__ 11  (required).</param>
        /// <param name="name">The legal name of the Token Requestor. __Max Length:__ 64  (required).</param>
        /// <param name="consumerFacingEntityName">The name of the Token Requestor to be displayed to the account holder. __Max Length:__ 100  (required).</param>
        /// <param name="imageAssetId">The image of the Token Requestor (for instance a logo). Provided as an Asset ID – use the Get Asset API to retrieve the actual asset. __Max Length:__ 64 .</param>
        /// <param name="tokenRequestorType">The type of the Token Requestor. __Max Length:__ 32. Must be either:  * MERCHANT: The Token Requestor is a Merchant  * WALLET: The Token Requestor is a Wallet or a Commerce Platform  (required).</param>
        /// <param name="walletId">The identifier of the Wallet Provider. __Length:__ 3 __Conditional,__ Only present when the token is provided to a Wallet Provider. Not present otherwise. .</param>
        /// <param name="enabledAccountRanges">Array of account range start numbers that are enabled for the Token Requestor.The start numbers will be 19 digits in length.  (required).</param>
        /// <param name="supportedPushMethods">Array of the push methods supported by the Token Requestor. __Conditional__. The array is not returned if the Token Requestor does not participate in MDES Token Connect Program. Possible push methods are:  * ANDROID: The Token Requestor supports app-to-app and web-to-app communication on Android.  * IOS: The Token Requestor supports app-to-app and web-to-app communication on iOS.  * WEB: The Token Requestor supports web-to-web or app-to-web communication. .</param>
        /// <param name="supportsMultiplePushedCards">Flag to indicate if Token Requestor supports multiple push account receipts in a single request. When supported, a maximum of 5 receipts may be sent to the Token Requestor in a single request __Conditional__. Must be present if the Token Requestor participates in MDES Token Connect program, not present otherwise. Must be either :  * true: Multiple push receipts are supported.  * false: Multiple push receipts are not supported. .</param>
        /// <param name="supportedAccountHolderData">List (array) of account holder data elements that the Token Requestor accepts to receive from the Issuer with a pushed card or account. __Conditional__. The array is not returned if the Token Requestor does not participate in MDES Token Connect Program. If the Token Requestor participates in MDES Token Connect but doesn&#39;t accept any account holder data then an empty array is returned. __To ensure forward-compatibility, all API client implementations must be resilient to new data element values being added to responses from MDES.__ Possible values are:  * \&quot;NAME\&quot;: The first name and last name of the account holder  * \&quot;ADDRESS\&quot;: The billing address for the account holder  * \&quot;EMAIL_ADDRESS\&quot;: The email address for the account holder  * \&quot;MOBILE_PHONE_NUMBER\&quot;: The mobile phone number for the account holder .</param>
        /// <param name="supportsCardHolderAuthentication">Flag to indicate if token requestor supports cardholder authentication after the token is activated. Must be one of:   * true - Post Tokenization Carholder Authentication (Consent Service) is supported.   * false - Post Tokenization Carholder Authentication (Consent Service) is not supported. .</param>
        /// <param name="supportsTokenConnect">A boolean parameter indicate that token requestor supports Token Connect or not. Must be one of: * true - Token Connect is supported * false - Token Connect is not supported .</param>
        /// <param name="availablePushMethods">Array of push methods supported by the token requestor..</param>
        public TokenRequestor(string tokenRequestorId = default(string), string name = default(string), string consumerFacingEntityName = default(string), string imageAssetId = default(string), string tokenRequestorType = default(string), string walletId = default(string), List<long> enabledAccountRanges = default(List<long>), List<string> supportedPushMethods = default(List<string>), bool supportsMultiplePushedCards = default(bool), List<string> supportedAccountHolderData = default(List<string>), bool supportsCardHolderAuthentication = default(bool), bool supportsTokenConnect = default(bool), List<PushMethod> availablePushMethods = default(List<PushMethod>))
        {
            // to ensure "tokenRequestorId" is required (not null)
            if (tokenRequestorId == null) {
                throw new ArgumentNullException("tokenRequestorId is a required property for TokenRequestor and cannot be null");
            }
            this.TokenRequestorId = tokenRequestorId;
            // to ensure "name" is required (not null)
            if (name == null) {
                throw new ArgumentNullException("name is a required property for TokenRequestor and cannot be null");
            }
            this.Name = name;
            // to ensure "consumerFacingEntityName" is required (not null)
            if (consumerFacingEntityName == null) {
                throw new ArgumentNullException("consumerFacingEntityName is a required property for TokenRequestor and cannot be null");
            }
            this.ConsumerFacingEntityName = consumerFacingEntityName;
            // to ensure "tokenRequestorType" is required (not null)
            if (tokenRequestorType == null) {
                throw new ArgumentNullException("tokenRequestorType is a required property for TokenRequestor and cannot be null");
            }
            this.TokenRequestorType = tokenRequestorType;
            // to ensure "enabledAccountRanges" is required (not null)
            if (enabledAccountRanges == null) {
                throw new ArgumentNullException("enabledAccountRanges is a required property for TokenRequestor and cannot be null");
            }
            this.EnabledAccountRanges = enabledAccountRanges;
            this.ImageAssetId = imageAssetId;
            this.WalletId = walletId;
            this.SupportedPushMethods = supportedPushMethods;
            this.SupportsMultiplePushedCards = supportsMultiplePushedCards;
            this.SupportedAccountHolderData = supportedAccountHolderData;
            this.SupportsCardHolderAuthentication = supportsCardHolderAuthentication;
            this.SupportsTokenConnect = supportsTokenConnect;
            this.AvailablePushMethods = availablePushMethods;
        }

        /// <summary>
        /// Identifies the Token Requestor where the Account must be pushed to. The string contains a 11-digit numeric value. __Length:__ 11 
        /// </summary>
        /// <value>Identifies the Token Requestor where the Account must be pushed to. The string contains a 11-digit numeric value. __Length:__ 11 </value>
        [DataMember(Name = "tokenRequestorId", IsRequired = true, EmitDefaultValue = false)]
        public string TokenRequestorId { get; set; }

        /// <summary>
        /// The legal name of the Token Requestor. __Max Length:__ 64 
        /// </summary>
        /// <value>The legal name of the Token Requestor. __Max Length:__ 64 </value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// The name of the Token Requestor to be displayed to the account holder. __Max Length:__ 100 
        /// </summary>
        /// <value>The name of the Token Requestor to be displayed to the account holder. __Max Length:__ 100 </value>
        [DataMember(Name = "consumerFacingEntityName", IsRequired = true, EmitDefaultValue = false)]
        public string ConsumerFacingEntityName { get; set; }

        /// <summary>
        /// The image of the Token Requestor (for instance a logo). Provided as an Asset ID – use the Get Asset API to retrieve the actual asset. __Max Length:__ 64 
        /// </summary>
        /// <value>The image of the Token Requestor (for instance a logo). Provided as an Asset ID – use the Get Asset API to retrieve the actual asset. __Max Length:__ 64 </value>
        [DataMember(Name = "imageAssetId", EmitDefaultValue = false)]
        public string ImageAssetId { get; set; }

        /// <summary>
        /// The type of the Token Requestor. __Max Length:__ 32. Must be either:  * MERCHANT: The Token Requestor is a Merchant  * WALLET: The Token Requestor is a Wallet or a Commerce Platform 
        /// </summary>
        /// <value>The type of the Token Requestor. __Max Length:__ 32. Must be either:  * MERCHANT: The Token Requestor is a Merchant  * WALLET: The Token Requestor is a Wallet or a Commerce Platform </value>
        [DataMember(Name = "tokenRequestorType", IsRequired = true, EmitDefaultValue = false)]
        public string TokenRequestorType { get; set; }

        /// <summary>
        /// The identifier of the Wallet Provider. __Length:__ 3 __Conditional,__ Only present when the token is provided to a Wallet Provider. Not present otherwise. 
        /// </summary>
        /// <value>The identifier of the Wallet Provider. __Length:__ 3 __Conditional,__ Only present when the token is provided to a Wallet Provider. Not present otherwise. </value>
        [DataMember(Name = "walletId", EmitDefaultValue = false)]
        public string WalletId { get; set; }

        /// <summary>
        /// Array of account range start numbers that are enabled for the Token Requestor.The start numbers will be 19 digits in length. 
        /// </summary>
        /// <value>Array of account range start numbers that are enabled for the Token Requestor.The start numbers will be 19 digits in length. </value>
        [DataMember(Name = "enabledAccountRanges", IsRequired = true, EmitDefaultValue = false)]
        public List<long> EnabledAccountRanges { get; set; }

        /// <summary>
        /// Array of the push methods supported by the Token Requestor. __Conditional__. The array is not returned if the Token Requestor does not participate in MDES Token Connect Program. Possible push methods are:  * ANDROID: The Token Requestor supports app-to-app and web-to-app communication on Android.  * IOS: The Token Requestor supports app-to-app and web-to-app communication on iOS.  * WEB: The Token Requestor supports web-to-web or app-to-web communication. 
        /// </summary>
        /// <value>Array of the push methods supported by the Token Requestor. __Conditional__. The array is not returned if the Token Requestor does not participate in MDES Token Connect Program. Possible push methods are:  * ANDROID: The Token Requestor supports app-to-app and web-to-app communication on Android.  * IOS: The Token Requestor supports app-to-app and web-to-app communication on iOS.  * WEB: The Token Requestor supports web-to-web or app-to-web communication. </value>
        [DataMember(Name = "supportedPushMethods", EmitDefaultValue = false)]
        public List<string> SupportedPushMethods { get; set; }

        /// <summary>
        /// Flag to indicate if Token Requestor supports multiple push account receipts in a single request. When supported, a maximum of 5 receipts may be sent to the Token Requestor in a single request __Conditional__. Must be present if the Token Requestor participates in MDES Token Connect program, not present otherwise. Must be either :  * true: Multiple push receipts are supported.  * false: Multiple push receipts are not supported. 
        /// </summary>
        /// <value>Flag to indicate if Token Requestor supports multiple push account receipts in a single request. When supported, a maximum of 5 receipts may be sent to the Token Requestor in a single request __Conditional__. Must be present if the Token Requestor participates in MDES Token Connect program, not present otherwise. Must be either :  * true: Multiple push receipts are supported.  * false: Multiple push receipts are not supported. </value>
        [DataMember(Name = "supportsMultiplePushedCards", EmitDefaultValue = true)]
        public bool SupportsMultiplePushedCards { get; set; }

        /// <summary>
        /// List (array) of account holder data elements that the Token Requestor accepts to receive from the Issuer with a pushed card or account. __Conditional__. The array is not returned if the Token Requestor does not participate in MDES Token Connect Program. If the Token Requestor participates in MDES Token Connect but doesn&#39;t accept any account holder data then an empty array is returned. __To ensure forward-compatibility, all API client implementations must be resilient to new data element values being added to responses from MDES.__ Possible values are:  * \&quot;NAME\&quot;: The first name and last name of the account holder  * \&quot;ADDRESS\&quot;: The billing address for the account holder  * \&quot;EMAIL_ADDRESS\&quot;: The email address for the account holder  * \&quot;MOBILE_PHONE_NUMBER\&quot;: The mobile phone number for the account holder 
        /// </summary>
        /// <value>List (array) of account holder data elements that the Token Requestor accepts to receive from the Issuer with a pushed card or account. __Conditional__. The array is not returned if the Token Requestor does not participate in MDES Token Connect Program. If the Token Requestor participates in MDES Token Connect but doesn&#39;t accept any account holder data then an empty array is returned. __To ensure forward-compatibility, all API client implementations must be resilient to new data element values being added to responses from MDES.__ Possible values are:  * \&quot;NAME\&quot;: The first name and last name of the account holder  * \&quot;ADDRESS\&quot;: The billing address for the account holder  * \&quot;EMAIL_ADDRESS\&quot;: The email address for the account holder  * \&quot;MOBILE_PHONE_NUMBER\&quot;: The mobile phone number for the account holder </value>
        [DataMember(Name = "supportedAccountHolderData", EmitDefaultValue = false)]
        public List<string> SupportedAccountHolderData { get; set; }

        /// <summary>
        /// Flag to indicate if token requestor supports cardholder authentication after the token is activated. Must be one of:   * true - Post Tokenization Carholder Authentication (Consent Service) is supported.   * false - Post Tokenization Carholder Authentication (Consent Service) is not supported. 
        /// </summary>
        /// <value>Flag to indicate if token requestor supports cardholder authentication after the token is activated. Must be one of:   * true - Post Tokenization Carholder Authentication (Consent Service) is supported.   * false - Post Tokenization Carholder Authentication (Consent Service) is not supported. </value>
        [DataMember(Name = "supportsCardHolderAuthentication", EmitDefaultValue = true)]
        public bool SupportsCardHolderAuthentication { get; set; }

        /// <summary>
        /// A boolean parameter indicate that token requestor supports Token Connect or not. Must be one of: * true - Token Connect is supported * false - Token Connect is not supported 
        /// </summary>
        /// <value>A boolean parameter indicate that token requestor supports Token Connect or not. Must be one of: * true - Token Connect is supported * false - Token Connect is not supported </value>
        [DataMember(Name = "supportsTokenConnect", EmitDefaultValue = true)]
        public bool SupportsTokenConnect { get; set; }

        /// <summary>
        /// Array of push methods supported by the token requestor.
        /// </summary>
        /// <value>Array of push methods supported by the token requestor.</value>
        [DataMember(Name = "availablePushMethods", EmitDefaultValue = false)]
        public List<PushMethod> AvailablePushMethods { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TokenRequestor {\n");
            sb.Append("  TokenRequestorId: ").Append(TokenRequestorId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ConsumerFacingEntityName: ").Append(ConsumerFacingEntityName).Append("\n");
            sb.Append("  ImageAssetId: ").Append(ImageAssetId).Append("\n");
            sb.Append("  TokenRequestorType: ").Append(TokenRequestorType).Append("\n");
            sb.Append("  WalletId: ").Append(WalletId).Append("\n");
            sb.Append("  EnabledAccountRanges: ").Append(EnabledAccountRanges).Append("\n");
            sb.Append("  SupportedPushMethods: ").Append(SupportedPushMethods).Append("\n");
            sb.Append("  SupportsMultiplePushedCards: ").Append(SupportsMultiplePushedCards).Append("\n");
            sb.Append("  SupportedAccountHolderData: ").Append(SupportedAccountHolderData).Append("\n");
            sb.Append("  SupportsCardHolderAuthentication: ").Append(SupportsCardHolderAuthentication).Append("\n");
            sb.Append("  SupportsTokenConnect: ").Append(SupportsTokenConnect).Append("\n");
            sb.Append("  AvailablePushMethods: ").Append(AvailablePushMethods).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TokenRequestor);
        }

        /// <summary>
        /// Returns true if TokenRequestor instances are equal
        /// </summary>
        /// <param name="input">Instance of TokenRequestor to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TokenRequestor input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TokenRequestorId == input.TokenRequestorId ||
                    (this.TokenRequestorId != null &&
                    this.TokenRequestorId.Equals(input.TokenRequestorId))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.ConsumerFacingEntityName == input.ConsumerFacingEntityName ||
                    (this.ConsumerFacingEntityName != null &&
                    this.ConsumerFacingEntityName.Equals(input.ConsumerFacingEntityName))
                ) && 
                (
                    this.ImageAssetId == input.ImageAssetId ||
                    (this.ImageAssetId != null &&
                    this.ImageAssetId.Equals(input.ImageAssetId))
                ) && 
                (
                    this.TokenRequestorType == input.TokenRequestorType ||
                    (this.TokenRequestorType != null &&
                    this.TokenRequestorType.Equals(input.TokenRequestorType))
                ) && 
                (
                    this.WalletId == input.WalletId ||
                    (this.WalletId != null &&
                    this.WalletId.Equals(input.WalletId))
                ) && 
                (
                    this.EnabledAccountRanges == input.EnabledAccountRanges ||
                    this.EnabledAccountRanges != null &&
                    input.EnabledAccountRanges != null &&
                    this.EnabledAccountRanges.SequenceEqual(input.EnabledAccountRanges)
                ) && 
                (
                    this.SupportedPushMethods == input.SupportedPushMethods ||
                    this.SupportedPushMethods != null &&
                    input.SupportedPushMethods != null &&
                    this.SupportedPushMethods.SequenceEqual(input.SupportedPushMethods)
                ) && 
                (
                    this.SupportsMultiplePushedCards == input.SupportsMultiplePushedCards ||
                    this.SupportsMultiplePushedCards.Equals(input.SupportsMultiplePushedCards)
                ) && 
                (
                    this.SupportedAccountHolderData == input.SupportedAccountHolderData ||
                    this.SupportedAccountHolderData != null &&
                    input.SupportedAccountHolderData != null &&
                    this.SupportedAccountHolderData.SequenceEqual(input.SupportedAccountHolderData)
                ) && 
                (
                    this.SupportsCardHolderAuthentication == input.SupportsCardHolderAuthentication ||
                    this.SupportsCardHolderAuthentication.Equals(input.SupportsCardHolderAuthentication)
                ) && 
                (
                    this.SupportsTokenConnect == input.SupportsTokenConnect ||
                    this.SupportsTokenConnect.Equals(input.SupportsTokenConnect)
                ) && 
                (
                    this.AvailablePushMethods == input.AvailablePushMethods ||
                    this.AvailablePushMethods != null &&
                    input.AvailablePushMethods != null &&
                    this.AvailablePushMethods.SequenceEqual(input.AvailablePushMethods)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TokenRequestorId != null)
                    hashCode = hashCode * 59 + this.TokenRequestorId.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.ConsumerFacingEntityName != null)
                    hashCode = hashCode * 59 + this.ConsumerFacingEntityName.GetHashCode();
                if (this.ImageAssetId != null)
                    hashCode = hashCode * 59 + this.ImageAssetId.GetHashCode();
                if (this.TokenRequestorType != null)
                    hashCode = hashCode * 59 + this.TokenRequestorType.GetHashCode();
                if (this.WalletId != null)
                    hashCode = hashCode * 59 + this.WalletId.GetHashCode();
                if (this.EnabledAccountRanges != null)
                    hashCode = hashCode * 59 + this.EnabledAccountRanges.GetHashCode();
                if (this.SupportedPushMethods != null)
                    hashCode = hashCode * 59 + this.SupportedPushMethods.GetHashCode();
                hashCode = hashCode * 59 + this.SupportsMultiplePushedCards.GetHashCode();
                if (this.SupportedAccountHolderData != null)
                    hashCode = hashCode * 59 + this.SupportedAccountHolderData.GetHashCode();
                hashCode = hashCode * 59 + this.SupportsCardHolderAuthentication.GetHashCode();
                hashCode = hashCode * 59 + this.SupportsTokenConnect.GetHashCode();
                if (this.AvailablePushMethods != null)
                    hashCode = hashCode * 59 + this.AvailablePushMethods.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
